# Site settings
title: Temple Data Science Institute
email: dsi@temple.edu
description: > # this means to ignore newlines until "baseurl:"
  The Data Science Institute at Temple University advances data science research, education, and partnerships to address real-world challenges.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://templedsi.github.io" # the base hostname & protocol for your site
# github_username: templedsi
# twitter_username: templeDSI

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
